FROM debian:9

RUN apt-get -qq update && apt-get install -y -qq git sudo realpath ipmitool libtool automake re2c tclx build-essential libreadline-dev libxt-dev x11proto-print-dev libxmu-headers libxmu-dev libxmu6 libxpm-dev libxmuu-dev libxmuu1 libpcre++-dev libsnmp-dev re2c darcs python-dev libxml2-dev libusb-dev libusb-1.0-0-dev libudev-dev
